// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message/RpcMsg.proto

package org.neep.rpc.msg.entity;

public final class RpcMsg {
  private RpcMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes content = 1;</code>
     */
    com.google.protobuf.ByteString getContent();

    /**
     * <code>bool result = 2;</code>
     */
    boolean getResult();

    /**
     * <code>string resultText = 3;</code>
     */
    String getResultText();
    /**
     * <code>string resultText = 3;</code>
     */
    com.google.protobuf.ByteString
        getResultTextBytes();

    /**
     * <code>string msgType = 4;</code>
     */
    String getMsgType();
    /**
     * <code>string msgType = 4;</code>
     */
    com.google.protobuf.ByteString
        getMsgTypeBytes();

    /**
     * <code>string classType = 5;</code>
     */
    String getClassType();
    /**
     * <code>string classType = 5;</code>
     */
    com.google.protobuf.ByteString
        getClassTypeBytes();

    /**
     * <code>string serviceUrl = 6;</code>
     */
    String getServiceUrl();
    /**
     * <code>string serviceUrl = 6;</code>
     */
    com.google.protobuf.ByteString
        getServiceUrlBytes();
  }
  /**
   * Protobuf type {@code proto.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      content_ = com.google.protobuf.ByteString.EMPTY;
      result_ = false;
      resultText_ = "";
      msgType_ = "";
      classType_ = "";
      serviceUrl_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              content_ = input.readBytes();
              break;
            }
            case 16: {

              result_ = input.readBool();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              resultText_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              msgType_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              classType_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              serviceUrl_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.neep.rpc.msg.entity.RpcMsg.internal_static_proto_Message_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.neep.rpc.msg.entity.RpcMsg.internal_static_proto_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.neep.rpc.msg.entity.RpcMsg.Message.class, org.neep.rpc.msg.entity.RpcMsg.Message.Builder.class);
    }

    public static final int CONTENT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 1;</code>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private boolean result_;
    /**
     * <code>bool result = 2;</code>
     */
    public boolean getResult() {
      return result_;
    }

    public static final int RESULTTEXT_FIELD_NUMBER = 3;
    private volatile Object resultText_;
    /**
     * <code>string resultText = 3;</code>
     */
    public String getResultText() {
      Object ref = resultText_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        resultText_ = s;
        return s;
      }
    }
    /**
     * <code>string resultText = 3;</code>
     */
    public com.google.protobuf.ByteString
        getResultTextBytes() {
      Object ref = resultText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        resultText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGTYPE_FIELD_NUMBER = 4;
    private volatile Object msgType_;
    /**
     * <code>string msgType = 4;</code>
     */
    public String getMsgType() {
      Object ref = msgType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        msgType_ = s;
        return s;
      }
    }
    /**
     * <code>string msgType = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMsgTypeBytes() {
      Object ref = msgType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        msgType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASSTYPE_FIELD_NUMBER = 5;
    private volatile Object classType_;
    /**
     * <code>string classType = 5;</code>
     */
    public String getClassType() {
      Object ref = classType_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        classType_ = s;
        return s;
      }
    }
    /**
     * <code>string classType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getClassTypeBytes() {
      Object ref = classType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        classType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICEURL_FIELD_NUMBER = 6;
    private volatile Object serviceUrl_;
    /**
     * <code>string serviceUrl = 6;</code>
     */
    public String getServiceUrl() {
      Object ref = serviceUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serviceUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string serviceUrl = 6;</code>
     */
    public com.google.protobuf.ByteString
        getServiceUrlBytes() {
      Object ref = serviceUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!content_.isEmpty()) {
        output.writeBytes(1, content_);
      }
      if (result_ != false) {
        output.writeBool(2, result_);
      }
      if (!getResultTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, resultText_);
      }
      if (!getMsgTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, msgType_);
      }
      if (!getClassTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, classType_);
      }
      if (!getServiceUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, serviceUrl_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, content_);
      }
      if (result_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, result_);
      }
      if (!getResultTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, resultText_);
      }
      if (!getMsgTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, msgType_);
      }
      if (!getClassTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, classType_);
      }
      if (!getServiceUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, serviceUrl_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.neep.rpc.msg.entity.RpcMsg.Message)) {
        return super.equals(obj);
      }
      org.neep.rpc.msg.entity.RpcMsg.Message other = (org.neep.rpc.msg.entity.RpcMsg.Message) obj;

      boolean result = true;
      result = result && getContent()
          .equals(other.getContent());
      result = result && (getResult()
          == other.getResult());
      result = result && getResultText()
          .equals(other.getResultText());
      result = result && getMsgType()
          .equals(other.getMsgType());
      result = result && getClassType()
          .equals(other.getClassType());
      result = result && getServiceUrl()
          .equals(other.getServiceUrl());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getResult());
      hash = (37 * hash) + RESULTTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getResultText().hashCode();
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType().hashCode();
      hash = (37 * hash) + CLASSTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getClassType().hashCode();
      hash = (37 * hash) + SERVICEURL_FIELD_NUMBER;
      hash = (53 * hash) + getServiceUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.neep.rpc.msg.entity.RpcMsg.Message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.neep.rpc.msg.entity.RpcMsg.Message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.neep.rpc.msg.entity.RpcMsg.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.neep.rpc.msg.entity.RpcMsg.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.neep.rpc.msg.entity.RpcMsg.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.neep.rpc.msg.entity.RpcMsg.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.neep.rpc.msg.entity.RpcMsg.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.neep.rpc.msg.entity.RpcMsg.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.neep.rpc.msg.entity.RpcMsg.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.neep.rpc.msg.entity.RpcMsg.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.neep.rpc.msg.entity.RpcMsg.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.neep.rpc.msg.entity.RpcMsg.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.neep.rpc.msg.entity.RpcMsg.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Message)
        org.neep.rpc.msg.entity.RpcMsg.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.neep.rpc.msg.entity.RpcMsg.internal_static_proto_Message_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.neep.rpc.msg.entity.RpcMsg.internal_static_proto_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.neep.rpc.msg.entity.RpcMsg.Message.class, org.neep.rpc.msg.entity.RpcMsg.Message.Builder.class);
      }

      // Construct using org.neep.rpc.msg.entity.RpcMsg.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        content_ = com.google.protobuf.ByteString.EMPTY;

        result_ = false;

        resultText_ = "";

        msgType_ = "";

        classType_ = "";

        serviceUrl_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.neep.rpc.msg.entity.RpcMsg.internal_static_proto_Message_descriptor;
      }

      public org.neep.rpc.msg.entity.RpcMsg.Message getDefaultInstanceForType() {
        return org.neep.rpc.msg.entity.RpcMsg.Message.getDefaultInstance();
      }

      public org.neep.rpc.msg.entity.RpcMsg.Message build() {
        org.neep.rpc.msg.entity.RpcMsg.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.neep.rpc.msg.entity.RpcMsg.Message buildPartial() {
        org.neep.rpc.msg.entity.RpcMsg.Message result = new org.neep.rpc.msg.entity.RpcMsg.Message(this);
        result.content_ = content_;
        result.result_ = result_;
        result.resultText_ = resultText_;
        result.msgType_ = msgType_;
        result.classType_ = classType_;
        result.serviceUrl_ = serviceUrl_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.neep.rpc.msg.entity.RpcMsg.Message) {
          return mergeFrom((org.neep.rpc.msg.entity.RpcMsg.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.neep.rpc.msg.entity.RpcMsg.Message other) {
        if (other == org.neep.rpc.msg.entity.RpcMsg.Message.getDefaultInstance()) return this;
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        if (other.getResult() != false) {
          setResult(other.getResult());
        }
        if (!other.getResultText().isEmpty()) {
          resultText_ = other.resultText_;
          onChanged();
        }
        if (!other.getMsgType().isEmpty()) {
          msgType_ = other.msgType_;
          onChanged();
        }
        if (!other.getClassType().isEmpty()) {
          classType_ = other.classType_;
          onChanged();
        }
        if (!other.getServiceUrl().isEmpty()) {
          serviceUrl_ = other.serviceUrl_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.neep.rpc.msg.entity.RpcMsg.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.neep.rpc.msg.entity.RpcMsg.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 1;</code>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 1;</code>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }

        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 1;</code>
       */
      public Builder clearContent() {

        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      private boolean result_ ;
      /**
       * <code>bool result = 2;</code>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>bool result = 2;</code>
       */
      public Builder setResult(boolean value) {

        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool result = 2;</code>
       */
      public Builder clearResult() {

        result_ = false;
        onChanged();
        return this;
      }

      private Object resultText_ = "";
      /**
       * <code>string resultText = 3;</code>
       */
      public String getResultText() {
        Object ref = resultText_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          resultText_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string resultText = 3;</code>
       */
      public com.google.protobuf.ByteString
          getResultTextBytes() {
        Object ref = resultText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          resultText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string resultText = 3;</code>
       */
      public Builder setResultText(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        resultText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string resultText = 3;</code>
       */
      public Builder clearResultText() {

        resultText_ = getDefaultInstance().getResultText();
        onChanged();
        return this;
      }
      /**
       * <code>string resultText = 3;</code>
       */
      public Builder setResultTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        resultText_ = value;
        onChanged();
        return this;
      }

      private Object msgType_ = "";
      /**
       * <code>string msgType = 4;</code>
       */
      public String getMsgType() {
        Object ref = msgType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          msgType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string msgType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMsgTypeBytes() {
        Object ref = msgType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          msgType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msgType = 4;</code>
       */
      public Builder setMsgType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msgType = 4;</code>
       */
      public Builder clearMsgType() {

        msgType_ = getDefaultInstance().getMsgType();
        onChanged();
        return this;
      }
      /**
       * <code>string msgType = 4;</code>
       */
      public Builder setMsgTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        msgType_ = value;
        onChanged();
        return this;
      }

      private Object classType_ = "";
      /**
       * <code>string classType = 5;</code>
       */
      public String getClassType() {
        Object ref = classType_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          classType_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string classType = 5;</code>
       */
      public com.google.protobuf.ByteString
          getClassTypeBytes() {
        Object ref = classType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          classType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string classType = 5;</code>
       */
      public Builder setClassType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        classType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string classType = 5;</code>
       */
      public Builder clearClassType() {

        classType_ = getDefaultInstance().getClassType();
        onChanged();
        return this;
      }
      /**
       * <code>string classType = 5;</code>
       */
      public Builder setClassTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        classType_ = value;
        onChanged();
        return this;
      }

      private Object serviceUrl_ = "";
      /**
       * <code>string serviceUrl = 6;</code>
       */
      public String getServiceUrl() {
        Object ref = serviceUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serviceUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string serviceUrl = 6;</code>
       */
      public com.google.protobuf.ByteString
          getServiceUrlBytes() {
        Object ref = serviceUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serviceUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serviceUrl = 6;</code>
       */
      public Builder setServiceUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        serviceUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serviceUrl = 6;</code>
       */
      public Builder clearServiceUrl() {

        serviceUrl_ = getDefaultInstance().getServiceUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string serviceUrl = 6;</code>
       */
      public Builder setServiceUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        serviceUrl_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:proto.Message)
    }

    // @@protoc_insertion_point(class_scope:proto.Message)
    private static final org.neep.rpc.msg.entity.RpcMsg.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.neep.rpc.msg.entity.RpcMsg.Message();
    }

    public static org.neep.rpc.msg.entity.RpcMsg.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public org.neep.rpc.msg.entity.RpcMsg.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Message_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024message/RpcMsg.proto\022\005proto\"v\n\007Message" +
      "\022\017\n\007content\030\001 \001(\014\022\016\n\006result\030\002 \001(\010\022\022\n\nres" +
      "ultText\030\003 \001(\t\022\017\n\007msgType\030\004 \001(\t\022\021\n\tclassT" +
      "ype\030\005 \001(\t\022\022\n\nserviceUrl\030\006 \001(\tB#\n\027org.nee" +
      "p.rpc.msg.entityB\006RpcMsgP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Message_descriptor,
        new String[] { "Content", "Result", "ResultText", "MsgType", "ClassType", "ServiceUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
